Prerequis
=================
```{r, warning=FALSE}
library(sciplot)
library(brms)
library(tidyverse)
library(ggplot2)
```

```{r}
setwd("C:/Users/antoi/Google Drive/Memoire2/R/comp1")
data <- read.csv(file="datacomp1.csv", header=TRUE, sep=",")
```



Overall
=================
```{r}
bargraph.CI(x.factor=typeverbe, group= prompt,response=comp.graph, col=c("tomato", "dark blue"), xlab="Verb type, 1",ylab="NP1 comp.graph %",legend=TRUE,  x.leg=3,y.leg=0.8 , cex.leg=1.3, cex.names=1, cex.lab = 1.5, ylim = c(0,1), data=data)
```

```{r}
mean(data$comp.graph[data$typeverbe == "percep" & data$prompt == "high"])
mean(data$comp.graph[data$typeverbe == "percep" & data$prompt == "low"])
mean(data$comp.graph[data$typeverbe == "stat" & data$prompt == "high"])
mean(data$comp.graph[data$typeverbe == "stat" & data$prompt == "low"])
```

```{r}
data$RT.equation <- as.numeric(data$RT.equation)
median_overall <- median(data$RT.equation)
data.lent <- subset(data, data$RT.equation > median_overall)
data.rapide <- subset(data, data$RT.equation < median_overall)
```

```{r}
bargraph.CI(x.factor=typeverbe, group= prompt,response=comp.graph, col=c("tomato", "dark blue"), xlab="Verb type (fast equation), 2",ylab="NP1 comp.graph %",legend=TRUE,  x.leg=3,y.leg=0.8 , cex.leg=1.3, cex.names=1, cex.lab = 1.5, ylim = c(0,1), data=data.rapide)
```

```{r}
mean(data.rapide$comp.graph[data.rapide$typeverbe == "percep" & data.rapide$prompt == "high"])
mean(data.rapide$comp.graph[data.rapide$typeverbe == "percep" & data.rapide$prompt == "low"])
mean(data.rapide$comp.graph[data.rapide$typeverbe == "stat" & data.rapide$prompt == "high"])
mean(data.rapide$comp.graph[data.rapide$typeverbe == "stat" & data.rapide$prompt == "low"])
```

```{r}
bargraph.CI(x.factor=typeverbe, group= prompt,response=comp.graph, col=c("tomato", "dark blue"), xlab="Verb type (slow equation), 2",ylab="NP1 comp.graph %",legend=TRUE,  x.leg=3,y.leg=0.8 , cex.leg=1.3, cex.names=1, cex.lab = 1.5, ylim = c(0,1), data=data.lent)
```

```{r}
mean(data.lent$comp.graph[data.lent$typeverbe == "percep" & data.lent$prompt == "high"])
mean(data.lent$comp.graph[data.lent$typeverbe == "percep" & data.lent$prompt == "low"])
mean(data.lent$comp.graph[data.lent$typeverbe == "stat" & data.lent$prompt == "high"])
mean(data.lent$comp.graph[data.lent$typeverbe == "stat" & data.lent$prompt == "low"])
```

```{r}
data$vt <- ifelse(data$typeverbe=="stat", -1, 1)
data$pr <- ifelse(data$prompt=="high", -1, 1)
data$cor <- ifelse(data$cor.equation=="0.5", -1, 1)
data$RT.equation <- as.numeric(data$RT.equation)
median.overall <- median(data$RT.equation)
data$slow <- ifelse(data$RT.equation < median.overall, -1, 1)
median.age <- median(data$age.y)
data$ag <- ifelse(data$age.y < median.age, -1, 1)
```

```{r}
get_prior(comp.graph ~ vt*pr*slow + (vt*pr*slow|id) + (vt*pr*slow|Item), data=data, family=bernoulli)
  
prior <- c(set_prior("normal(0,10)", class="b"),
             set_prior("normal(0,10)", class="Intercept"),
             set_prior("normal(0,10)", class="sd"),
             set_prior("lkj(2)", class="cor"))
```

```{r}
fit <- brm(comp.graph ~ 1+vt*pr*slow + (1+vt*pr*slow|id) + (1+vt*pr*slow|Item), data=data, family=bernoulli, 
             prior=prior, chains=4, iter=3000)
```

```{r}
summary(fit, waic=T)
```

```{r}
fit_df <- as.data.frame(fit)
beta <- fit_df[,grepl("b_",colnames(fit_df))]
beta <- beta[,-1]
  

df.overall.noage <- gather(beta, key=effect, value=beta, 1:ncol(beta)) %>%
    group_by(effect=as.factor(effect)) %>% 
    summarize(mean=mean(beta), # mean
              prob_greater=mean(beta>0), prob_smaller=mean(beta<0), # probability greater / smaller than zero
              min=min(beta), max=max(beta), # min and max values
              l95=unname(quantile(beta,probs=0.025)), # lower 95% credible intervals boundary
              h95=unname(quantile(beta,probs=0.975)), # upper 95% CrI boundary
              l85=unname(quantile(beta,probs=0.075)), # lower 85% CrI boundary
              h85=unname(quantile(beta,probs=0.925))) # upper 85% CrI boundary
  
levord <- colnames(beta)[1:ncol(beta)]
df.overall.noage$effect <- factor(df.overall.noage$effect, levels=levord)
df.overall.noage <- arrange(df.overall.noage, effect)
```

```{r}
df.overall.noage
write.csv(df.overall.noage, file = "df.overall.noage.csv")
```

```{r}
ggplot(data=df.overall.noage, aes(x=mean, y=effect)) + theme_bw() +
   ggtitle("Overall, 1") +
    geom_vline(aes(xintercept=0), size=1, linetype=2, col=gray(0.2)) + 
    geom_errorbarh(aes(xmax=max, xmin=min),height=0, size=1.2, col="#009E73") +
    geom_errorbarh(aes(xmax=l95, xmin=h95),linetype=1,height=0.2,size=1.5,col="#D55E00") +
    geom_errorbarh(aes(xmax=l85, xmin=h85),linetype=1,height=0.1,size=1.4,col="#56B4E9") +
    geom_point(size=4) + 
    scale_y_discrete(limits=rev(df.overall.noage$effect))
```

