
```{r, warning=FALSE}
library(sciplot)
library(brms)
library(tidyverse)
library(ggplot2)
```

```{r}
setwd("C:/Users/antoi/Google Drive/Memoire2/R/comp3")
data <- read.csv(file="Datacomp3.csv", header=TRUE, sep=",")
```

```{r}
data$pr <- ifelse(data$prime==1, -1, 1)
data$cor <- ifelse(data$cor.equation==1, -1, 1)
data$RT.equation <- as.numeric(data$RT.equation)
```


Overall
=================


```{r}
png("31.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (Overall), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=data)
dev.off()
```




```{r}
data$RT.equation <- as.numeric(data$RT.equation)
median.overall <- median(data$RT.equation)
data.lent <- subset(data, data$RT.equation > median.overall)
data.rapide <- subset(data, data$RT.equation < median.overall)
```



```{r}
png("32.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (Overall, fast equation), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=data.rapide)
dev.off()
```



```{r}
png("33.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (Overall, slow equation), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=data.lent)
dev.off()
```



```{r}
median.overall <- median(data$RT.equation)
data$slow <- ifelse(data$RT.equation < median.overall, -1, 1)
```


low math < 14
=================

```{r}
datamath <- subset(data, data$amount.cor.equation < 13.3)
```


```{r}
png("3nul1.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (mathematically non-skillful group), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=datamath)
dev.off()
```



```{r}
median.math <- median(datamath$RT.equation)
datamath.lent <- subset(datamath, datamath$RT.equation > median.math)
datamath.rapide <- subset(datamath, datamath$RT.equation < median.math)
```

```{r}
png("3nul2.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (mathematically non-skillful group, fast equations), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=datamath.rapide)
dev.off()
```



```{r}
png("3nul3.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (mathematically non-skillful group, slow equation), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=datamath.lent)
dev.off()
```





High math > 14
=================

```{r}
datamath <- subset(data, data$amount.cor.equation > 13.3)
```


```{r}
png("34.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (highly mathematically skillful group), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=datamath)
dev.off()
```



```{r}
median.math <- median(datamath$RT.equation)
datamath.lent <- subset(datamath, datamath$RT.equation > median.math)
datamath.rapide <- subset(datamath, datamath$RT.equation < median.math)
```


```{r}
png("35.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (highly mathematically skillful group, fast equations), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=datamath.rapide)
dev.off()
```



```{r}
png("36.png", width = 870, height = 560)
bargraph.CI(x.factor=prompt,response=attachment, col=c("tomato", "dark blue"), xlab="Prime (highly mathematically skillful group, slow equation), 3",ylab="NP1 attachment proportion",legend=TRUE,  x.leg=3,y.leg=1 , cex.leg=2, cex.names=2, cex.lab = 2, ylim = c(0,1), data=datamath.lent)
dev.off()
```


